Feature/issue/#11101007
morikun23/ToyBox pull request #27
Opened 2017-11-24 01:12 UTC by Kaihatsu-Hiroto

【ジャンプ台】作成完了プルリク

2017-11-25 20:05 UTC, morikun23 requested changes
ソースコードとソースファイル名の変更をお願いします。

2017-11-25 20:05 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/JumpRamp/Jumpramp.cs
> +        Animator m_anim;
一応アクセス修飾子は付けておきましょうか

2017-11-25 20:05 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/JumpRamp/Jumpramp.cs
> +            GameObject m_playercol;
メンバー変数ではないので `m_` は付けません。
メンバー変数って何かわかってるよね？？

2017-11-25 20:05 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/JumpRamp/Jumpramp.cs
> +        }
可読性を向上するためにここら辺は関数化しておきましょう。

2017-11-25 20:05 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/JumpRamp/Jumpramp.cs
> +    public class Jumpramp : MonoBehaviour
言葉のつなぎ目は大文字で区切りましょう。
クラス名の変更に伴い、ファイル名も忘れずに

2017-11-26 11:09 UTC, Kaihatsu-Hiroto commented
【ジャンプ台】変数名 ファイル名の変更完了

2017-11-26 14:25 UTC, merged