Feature/issue/15#11101006
morikun23/ToyBox pull request #28
Opened 2017-11-29 08:11 UTC by yoshiki-sato

確認お願いします

2017-12-01 19:03 UTC, morikun23 requested changes
作り直しを申します。
まず、第一にプレハブ化しておくこと。
次にCanvasを用いた作りにしないこと（理由は後日説明します）
ソースコードに対しても、とにかく可読性が悪いです。
コメントはもちろんのこと、変数名の付け方や、関数化などを徹底しましょう。（リーダブルコードを読めば解決）

2017-12-01 19:03 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/Elevator/ElevatorManager.cs
> +namespace ToyBox.Yoshiki
本番で使用するので、この名前空間は辞めよう

2017-12-01 19:03 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/Elevator/Elevator.cs
> +namespace ToyBox.Yoshiki
本番で使用するので、この名前空間は辞めよう

2017-12-01 19:03 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/Elevator/Elevator.cs
> +            if (m_nowPos == m_startPoint || m_nowPos == m_endPoint)
このようなif文で使用するような条件式は関数化した方が可読性が上がるので、試してみてください。
例えば、
 ``` 
if(IsMoveCompleted()){
    //処理
}

(省略)

bool IsMoveComleted(){
    return m_nowPos == m_startPoint || m_nowPos == m_endPoint;
}  
```
って書いてあったら、if文の条件が`移動が完了したら`と読めるでしょっ？

2017-12-01 19:03 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/Elevator/Elevator.cs
> +        //外部から作動させたい場合に
`///<summary>〜</summary>`の形式でコメントを書こう
でないと、コード予測補完ウィンドウにコメント内容が表示されないので。

2017-12-01 19:03 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/Elevator/Elevator.cs
> +            //各種オブジェの参照
複数行に渡って処理される内容に対してのコメントは
`#region ~ #endregion`の方がより親切です

2017-12-01 19:03 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/Elevator/Elevator.cs
> +            //TODO:プレハブへRigidbodyを追加させる
TODO系のコメントは書くのは自由（ていうかもっとやれ感）だが、
提出する時には、TODOの中身を完了させた上で該当するコメントを残さないようにしましょう。
（ただし、他人に対して`ここに処理を書いて`系は分かりやすいので残しておくべき）

2017-12-01 19:03 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/Elevator/Gate.cs
> +namespace ToyBox.Yoshiki
本番で使用するのでこの名前空間は辞めておこう

2017-12-01 19:03 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/Elevator/ElevatorManager.cs
> +        Elevator m_elevator;
アクセス修飾子は必ず書く癖を付けておこう
デフォルトが非公開なのは当然みんな知っているが、アクセス修飾子を書いてあげることで、より直感的であるため

2017-12-01 19:03 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/Elevator/Elevator.cs
> +        GameObject m_elevator;
これ実際に参照しているものは、`Collider`なわけだが、
Hierarchyが正しくないのか、この変数名が正しくないのかどちらなのだろうか？

2017-12-01 19:03 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/Elevator/Elevator.cs
> +        BoxCollider2D m_right;
この変数使われてないよね？消そう

2017-12-01 19:03 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/Elevator/ElevatorManager.cs
> +                else if(!m_isHit && m_isRide)
複雑な条件式（一目で分かりづらいもの）はコメントなり、関数化なりして可読性を上げよう

2017-12-01 19:03 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/Elevator/ElevatorManager.cs
> +        void OnDrawGizmos()
Editorのみ使用するので
`#if UNITY_EDITOR ~ #endif`で囲っておこう。
Editor以外（実機など）だとコンパイル対象から外れるのでわずかだが
処理速度、容量軽量化の向上に繋がります。

2017-12-01 19:03 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/Elevator/ElevatorManager.cs
> +        // Update is called once per frame
純粋なUpdate関数ではないので、このコメントは適さないはず

2017-12-01 19:03 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/Elevator/ElevatorManager.cs
> +    public class ElevatorManager : MonoBehaviour
Elevatorというオブジェクトの子に、Managerが存在するっておかしな設計になっていないかい？（あとそもそもやっている内容がManagerではない感）

2017-12-07 18:35 UTC, morikun23 requested changes
プレハブの作りはあれでOK
あとはコードの修正をお願いします。
特に、コメントが少ないのは何も変わっていないので。

2017-12-07 18:35 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/Elevator/Elevator.cs
> +            //#region ~ #endregion各種オブジェの参照
`#region`の使い方を間違えてる。一度ググってみて

2017-12-07 18:35 UTC, morikun23 commented on Assets/Scripts/Front/Gimmick/Elevator/Elevator.cs
> +            m_targetPos = m_endPoint;
35行目で`Vector2.zero`が代入されているのに、この処理はどういうことだろうか？
必要ないのであれば、どちらかを削除しよう

2017-12-08 00:46 UTC, yoshiki-sato commented
修正しました。確認お願いします

2017-12-08 01:50 UTC, morikun23 approved these changes

2017-12-08 01:51 UTC, merged