【Input】InputManagerとMobileInputの機能統合
morikun23/ToyBox pull request #30
Opened 2017-12-04 04:17 UTC by naonosuke8267

した。
適用するにはMainシーンを少しばかりいじる必要がありまして

2017-12-07 18:53 UTC, morikun23 requested changes
コメントを付けるだけで終了でよさそうです。
あとは、Mainシーンの設計について直接お話ししましょう

2017-12-07 18:53 UTC, morikun23 commented on Assets/Scripts/Framework/Input/InputManager.cs
> +		public int GetMaxHeirarchy(){
公開する関数には`<summary>`系のコメントを振ってあげるとコード補完ウィンドウに出力されるので、親切かと

2017-12-07 18:53 UTC, morikun23 commented on Assets/Scripts/Framework/Input/InputManager.cs
> +		public Playable GetPlayableCharactor(){
公開する関数には<summary>系のコメントを振ってあげるとコード補完ウィンドウに出力されるので、親切かと

2017-12-07 18:53 UTC, morikun23 commented on Assets/Scripts/Framework/Input/InputManager.cs
> +		public void UpdateByFrame() {
Singletonで実装するのなら、ここらへんは非公開メンバにして
コルーチンもしくは純粋なUpdate関数などで独自で更新させた方がいいかも

2017-12-07 18:53 UTC, morikun23 commented on Assets/Scripts/Framework/Input/InputManager.cs
> +		//root/hoge/fuga/TouchActorとツリーが出来ているなら、値は３と入力します
結構重量なコメントになっているので、`ToolTip("  ")`のAttributeを付けてあげよう
`Tooltip`とは、Inspectorにコメントを表示させるエディター機能のことです。

2017-12-08 00:53 UTC, naonosuke8267 commented
各レビュー内容に対応しました。

2017-12-08 01:00 UTC, naonosuke8267 commented
アクセス修飾子付与しますた

2017-12-08 01:45 UTC, morikun23 approved these changes
OK
あとは、Mainシーンに反映させる感じかな

2017-12-08 01:46 UTC, merged