【フレームワーク/EventManager】一部足りない部分を追加修正しました
morikun23/ToyBox pull request #58
Opened 2018-01-12 06:10 UTC by yoshiki-sato

Playerの情報とGimmickの情報を持たせるようにしました。

2018-01-12 06:51 UTC, morikun23 requested changes
不要な引数があるので、修正をお願いします。

2018-01-12 06:51 UTC, morikun23 commented on Assets/Scripts/Framework/Events/EventManager.cs
> +        public void SetEvent(IEvent arg_nextEvent,GameObject arg_gimmick,GameObject arg_playerObject)
PlayerObjectという引数は必要ないのでは？

2018-01-12 06:51 UTC, morikun23 commented on Assets/Scripts/Framework/Events/EventManager.cs
> +            m_player = arg_playerObject.GetComponent<Player>();
`if(m_player == null){
 m_player = FindObjectOfType<Player>();
}`
的な処理を書くだけで、わざわざ引数を設定させる手間が省けると思う
その際、プレイヤーが見つからなかったときの処理を用意することを忘れずに

2018-01-12 06:51 UTC, morikun23 commented on Assets/Scripts/Framework/Events/EventManager.cs
> +            m_player = arg_playerObject.GetComponent<Player>();
もしくは、プロパティを用意しておくのも手である

2018-01-13 14:53 UTC, yoshiki-sato commented
修正しました。確認お願いします。

2018-01-13 17:40 UTC, morikun23 approved these changes
OK！これでマージします

2018-01-13 17:41 UTC, merged